name: Deploy website

# on: push

on:
  push:
    branches:
      - 'publish-**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.0
      
      - name: "install dependence"
        run: |
          node --version
          yarn --version
          node ./scripts/_ci/fix-day.js
          yarn config list
          yarn install

      - name: build
        shell: bash
        run: bash ./scripts/_ci/deploy-pipelines.sh

      - name: deploy-to-surge
        uses: dswistowski/surge-sh-action@v1
        with:
          login: ${{ secrets.SURGE_LOGIN }}
          token: ${{ secrets.SURGE_TOKEN }}
          domain: https://ng-yunzai.surge.sh
          project: ./dist

      - name: Replace base href for gh-pages
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: '<base href="/">'
          replace: '<base href="/">'
          include: '*.html'
          regex: false

      - name: deploy-to-gh-pages
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./dist
        with:
          emptyCommits: false
